name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca3bffe3d89261cbecd1a811ddb18a13c1a1976efeafe39e7d793ee92a11d026"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
