name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52442405c6d2275ea8ea191ea3686c9cea91b01d59329815cc12a2a795dd4859"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
