name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5816429e867f6017664420a55ec23c33ffe6f49418caf4c3a243bc43764efe8"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
