name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9009efdce4799edda281a768dd53390ca6aeb108997f2c56c2c37e32f824a15"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
