name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bbb742e1416e0371abe0c3d63ae6f1f400c94f972dc7951fb8f1fe0937dd022"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
