name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ecd3baf3cf4d39e5bc62c32e9168aa2fe5203269f704e3c85eddeb95a7d3b8b"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
