name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f01d3e1ff78455371378b7e91b9ea9703f2d2f34f65728646214a9522552f4a9"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
