name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b002c20f2e14c4748ab923740bfdef65f21deb979f6901799a0d9c3f6a98ba3a"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
