name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b96e02737bda75ef2f7e8ad64e93f0814e50fecf5ad5acbff9babf9c537d003"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
