name = "2022 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47c96c2ac593a5d338cc7cad4e5e7e8746a9f820cf14dbf516027cbe74dc855d"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
