name = "BackSlot"
filename = "backslot-1.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3592/327/backslot-1.2.4.jar"
hash-format = "murmur2"
hash = "1420168974"

[update]
[update.curseforge]
file-id = 3592327
project-id = 402739
