name = "Caracal Mod"
filename = "caracal-1.18-1.3.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/9/caracal-1.18-1.3.5.1.jar"
hash-format = "murmur2"
hash = "510369179"

[update]
[update.curseforge]
file-id = 3580009
project-id = 486505
