name = "Chirpy's Wildlife"
filename = "wildlife-1.18-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3625/183/wildlife-1.18-1.0.jar"
hash-format = "murmur2"
hash = "934639233"

[update]
[update.curseforge]
file-id = 3625183
project-id = 568457
