name = "Controlling"
filename = "Controlling-fabric-1.18.1-9.0+14.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3627/69/Controlling-fabric-1.18.1-9.0+14.jar"
hash-format = "murmur2"
hash = "737910866"

[update]
[update.curseforge]
file-id = 3627069
project-id = 250398
