name = "Crawl (Fabric)"
filename = "crawl-0.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3621/981/crawl-0.10.2.jar"
hash-format = "murmur2"
hash = "2295481972"

[update]
[update.curseforge]
file-id = 3621981
project-id = 314579
