name = "Creeper Overhaul"
filename = "creeperoverhaul-1.18.1-0.3.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3627/416/creeperoverhaul-1.18.1-0.3.0-fabric.jar"
hash-format = "murmur2"
hash = "1519138043"

[update]
[update.curseforge]
file-id = 3627416
project-id = 561625
