name = "Enhanced Celestials(Fabric) - Blood Moons & Harvest Moons"
filename = "enhancedcelestials-1.18-2.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/569/enhancedcelestials-1.18-2.0.6.jar"
hash-format = "murmur2"
hash = "4207368781"

[update]
[update.curseforge]
file-id = 3542569
project-id = 443694
