name = "Fabric Waystones"
filename = "wraith-waystones-2.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/659/wraith-waystones-2.5.0.jar"
hash-format = "sha1"
hash = "5b2f3576361a61cf1f5eca1777b58595bfcf50b1"

[update]
[update.curseforge]
file-id = 3672659
project-id = 410902
