name = "FallingTree (Forge&Fabric)"
filename = "FallingTree-1.18.1-3.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/272/FallingTree-1.18.1-3.2.0.jar"
hash-format = "murmur2"
hash = "70210924"

[update]
[update.curseforge]
file-id = 3636272
project-id = 349559
