name = "FallingTree (Forge&Fabric)"
filename = "FallingTree-1.18.1-3.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3640/237/FallingTree-1.18.1-3.2.1.jar"
hash-format = "murmur2"
hash = "573578173"

[update]
[update.curseforge]
file-id = 3640237
project-id = 349559
