name = "IMBlockerFabric"
filename = "imblockerfabric-1.0.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3722/150/imblockerfabric-1.0.18.jar"
hash-format = "sha1"
hash = "b920363bc0e74982af5ef61e6e8813186549d542"

[update]
[update.curseforge]
file-id = 3722150
project-id = 399225
