name = "Improved Mobs (Fabric)"
filename = "improvedmobs-1.18.2-1.10.7-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3717/370/improvedmobs-1.18.2-1.10.7-fabric.jar"
hash-format = "sha1"
hash = "ab2f03b16d84ef35ad1904e4cd012630fc4951a6"

[update]
[update.curseforge]
file-id = 3717370
project-id = 552968
