name = "Improved Mobs (Fabric)"
filename = "improvedmobs-1.18.1-1.10.3-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/369/improvedmobs-1.18.1-1.10.3-fabric.jar"
hash-format = "sha1"
hash = "2683f123f8c0ce00821d7f3e12837b8cf8e010c7"

[update]
[update.curseforge]
file-id = 3667369
project-id = 552968
