name = "Interactic"
filename = "interactic-0.1.8+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3627/132/interactic-0.1.8+1.18.jar"
hash-format = "murmur2"
hash = "2151966206"

[update]
[update.curseforge]
file-id = 3627132
project-id = 510974
