name = "Interactic"
filename = "interactic-0.1.10+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3704/143/interactic-0.1.10+1.18.jar"
hash-format = "sha1"
hash = "f1cc9344d76bf134af7dc865a800a770b4ff8ab1"

[update]
[update.curseforge]
file-id = 3704143
project-id = 510974
