name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.3.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3647/297/InventoryProfilesNext-fabric-1.18-1.3.2.jar"
hash-format = "murmur2"
hash = "4043984548"

[update]
[update.curseforge]
file-id = 3647297
project-id = 495267
