name = "MmmMmmMmmMmm (Target Dummy)"
filename = "MmmMmmMmmMmm-1.18-1.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3642/328/MmmMmmMmmMmm-1.18-1.5.1.jar"
hash-format = "murmur2"
hash = "3166138962"

[update]
[update.curseforge]
file-id = 3642328
project-id = 225738
