name = "NinjaPhenix's Container Library"
filename = "ninjaphenix-container-library-1.2.10+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/TIhTvPdy/versions/1.2.10+1.18-fabric/ninjaphenix-container-library-1.2.10+1.18.jar"
hash-format = "sha512"
hash = "72d2a0d3a8737ec98ed21d30173bac7889d85b0154d8a7873429760b28ed1572cf55b418036657248eb52b61f3de2ce6f392b80a0f02d3288c71c57326cbed9c"

[update]
[update.modrinth]
mod-id = "TIhTvPdy"
version = "qdTHRUTv"
