name = "Pick Up Notifier [Fabric]"
filename = "PickUpNotifier-v3.2.0-1.18.2-Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/362/PickUpNotifier-v3.2.0-1.18.2-Fabric.jar"
hash-format = "sha1"
hash = "88843c47d8e07a7bf772d21f6d93f41638ed47ac"

[update]
[update.curseforge]
file-id = 3671362
project-id = 547474
