name = "Reinforced Shulker Boxes"
filename = "reinforced-shulker-boxes-2.0.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3687/648/reinforced-shulker-boxes-2.0.0+1.18.jar"
hash-format = "sha1"
hash = "5ff8f47a01bd60683d01716d5bf60b71cdb9e9bf"

[update]
[update.curseforge]
file-id = 3687648
project-id = 529874
