name = "Reinforced Shulker Boxes"
filename = "reinforced-shulker-boxes-2.0.0-beta.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/985/reinforced-shulker-boxes-2.0.0-beta.2+1.18.jar"
hash-format = "murmur2"
hash = "3400274771"

[update]
[update.curseforge]
file-id = 3639985
project-id = 529874
