name = "Reinforced Chests"
filename = "reinforced-chests-2.0.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3687/647/reinforced-chests-2.0.0+1.18.jar"
hash-format = "sha1"
hash = "849a28bedab033f392cdf6f0650f48d2e942fbb7"

[update]
[update.curseforge]
file-id = 3687647
project-id = 529873
