name = "RPMTW Update Mod"
filename = "RPMTW-Update-Mod-Fabric-1.18.1-1.3.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3672/141/RPMTW-Update-Mod-Fabric-1.18.1-1.3.1.jar"
hash-format = "sha1"
hash = "e2e19d6cd5a453b6417d85208b12742d4000fa39"

[update]
[update.curseforge]
file-id = 3672141
project-id = 461500
