name = "SkyLib"
filename = "skylorlib-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3601/687/skylorlib-1.1.0.jar"
hash-format = "murmur2"
hash = "2622135802"

[update]
[update.curseforge]
file-id = 3601687
project-id = 513100
