name = "TenshiLib (Fabric)"
filename = "tenshilib-1.18.1-1.4.0b-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/620/tenshilib-1.18.1-1.4.0b-fabric.jar"
hash-format = "sha1"
hash = "9ad85e2a1e6171db2d39740dfef670565e574c63"

[update]
[update.curseforge]
file-id = 3609620
project-id = 552662
