name = "TenshiLib (Fabric)"
filename = "tenshilib-1.18.1-1.6.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/347/tenshilib-1.18.1-1.6.1-fabric.jar"
hash-format = "sha1"
hash = "194bac77d4690074cc8383ff7c816be599790c08"

[update]
[update.curseforge]
file-id = 3668347
project-id = 552662
