name = "TenshiLib (Fabric)"
filename = "tenshilib-1.18.2-1.6.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/229/tenshilib-1.18.2-1.6.5-fabric.jar"
hash-format = "sha1"
hash = "e03f1d8bec1ce3f6c463f7e67856876addedc9f5"

[update]
[update.curseforge]
file-id = 3707229
project-id = 552662
