name = "Waystones (Fabric Edition)"
filename = "waystones-fabric-1.18.1-9.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/152/waystones-fabric-1.18.1-9.0.3.jar"
hash-format = "murmur2"
hash = "758322976"

[update]
[update.curseforge]
file-id = 3606152
project-id = 500087
