name = "WTHIT"
filename = "wthit-fabric-4.5.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/879/wthit-fabric-4.5.2.jar"
hash-format = "sha1"
hash = "3618e4072c872d4e8eeb704a6696227cd4df3741"

[update]
[update.curseforge]
file-id = 3654879
project-id = 440979
